project:
  type: website
  output-dir: docs
  render:
    - "index.md" 
    - "rmarkdown/UNGDC_topic_modeling_updated.qmd"
    - "jupyter_notebook/functions_for_bert.ipynb"
 
  execute-dir: project
  
    
website:
  title: "UN General Debates Speech Analysis"
  sidebar:
    contents:
      - text: "Welcome"
        href: index.md
      - section: Topic Modeling
        contents:       
          - text: Topic Modeling 1
            href: rmarkdown/UNGDC_topic_modeling_updated.qmd
      - section: BERT
        contents:
          - text: BERT Functions
            href: jupyter_notebook/functions_for_bert.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



