project:
  type: website
  output-dir: docs
  render:
    - "index.md" 
    - "rmarkdown/UNGDC_topic_modeling_updated.qmd"
    - "rmarkdown/moving_lda_0219.qmd"
    - "rmarkdown/liwc_analysis.qmd" 
    - "jupyter_notebook/functions_for_bert.ipynb"
  

 
  execute-dir: project
  
bibliography: references.bib
    
website:
  title: "UN General Debates Speech Analysis"

  sidebar:
    contents:
      - text: "Welcome"
        href: index.md
      - section: Topic Modeling
        contents:       
          - text: Decadal LDA
            href: rmarkdown/UNGDC_topic_modeling_updated.qmd
          - text: Moving LDA
            href: rmarkdown/moving_lda_0219.qmd
     
      - section: Linguistic Analysis
        contents:
          - text: LIWC
            href: rmarkdown/liwc_analysis.qmd 
      - section: BERT
        contents:
          - text: BERT Functions
            href: jupyter_notebook/functions_for_bert.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



